before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      #- windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm: [6, 7]
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
