apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: execws
spec:
  homepage: https://github.com/jpts/kubectl-execws
  shortDescription: kubectl exec using WebSockets
  version: {{ .TagName }}
  description: |
    The kubectl execws plugin provides users the ability to exec over
    WebSockets. This provides compatiblity with loadbalancers which don't
    support the SPDY protocol. It also provides the ability to skip the
    need for the "get pods" RBAC permission and the ability to exec directly
    via a node, where direct connection to the apiserver is not available.
  caveats: |
    Node direct-exec functionality requires connection to the kubelet API to
    work, since it bypassess the apiserver by design.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/jpts/kubectl-execws/releases/download/{{ .TagName }}/kubectl-execws_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-execws
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/jpts/kubectl-execws/releases/download/{{ .TagName }}/kubectl-execws_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-execws
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/jpts/kubectl-execws/releases/download/{{ .TagName }}/kubectl-execws_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-execws
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/jpts/kubectl-execws/releases/download/{{ .TagName }}/kubectl-execws_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubectl-execws
  - selector:
      matchLabels:
        os: linux
        arch: arm
    {{addURIAndSha "https://github.com/jpts/kubectl-execws/releases/download/{{ .TagName }}/kubectl-execws_{{ .TagName }}_linux_armv6.tar.gz" .TagName }}
    bin: kubectl-execws
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/jpts/kubectl-execws/releases/download/{{ .TagName }}/kubectl-execws_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-execws.exe
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/jpts/kubectl-execws/releases/download/{{ .TagName }}/kubectl-execws_{{ .TagName }}_windows_arm64.tar.gz" .TagName }}
    bin: kubectl-execws.exe
